export interface Dorama {
  rank: number;
  title: string;
  original: string;
  imdb: number;
  adoroCinema?: number; // Score from 0 to 5
  popularity: number; // Global popularity index (0-100)
  averageScore: number; // Calculated metric for ranking
  year: number;
  description: string;
  image: string;
  category?: string;
  review?: string;
}

const calculateScore = (imdb: number, adoroCinema?: number) => {
  const ac = (adoroCinema || (imdb / 2)) * 20; // Normalize 0-5 to 0-100
  return parseFloat(((imdb * 10 + ac) / 2).toFixed(1));
};

export const TOP_DORAMAS: Dorama[] = [
  { 
    rank: 1, 
    title: "Reply 1988", 
    original: "Reply 1988", 
    imdb: 9.1, 
    adoroCinema: 4.9,
    popularity: 95,
    averageScore: 94.5,
    year: 2015,
    image: "/posters/poster-reply-1988.jpeg",
    description: "Cinco amigos de infância e suas famílias vivem no mesmo bairro em Seul no final dos anos 80.",
    category: "Família / Comédia",
    review: "Uma obra-prima absoluta. A forma como retrata a amizade e os laços familiares é inigualável. Prepare os lenços, mas também espere muitas risadas. É o meu dorama favorito da vida!"
  },
  { 
    rank: 2, 
    title: "My Mister", 
    original: "My Mister", 
    imdb: 9.1, 
    adoroCinema: 4.8,
    popularity: 90,
    averageScore: 93.5,
    year: 2018,
    image: "/posters/poster-my-mister.jpg",
    description: "Três irmãos de meia-idade e uma jovem mulher enfrentam as dificuldades da vida e encontram conforto uns nos outros.",
    category: "Drama / Psicológico",
    review: "Uma jornada emocional profunda e realista. A atuação é impecável e a história de superação e conexão humana é simplesmente linda. Um dorama que cura a alma."
  },
  { 
    rank: 3, 
    title: "Pousando no Amor", 
    original: "Crash Landing on You", 
    imdb: 8.7, 
    adoroCinema: 4.9,
    popularity: 98,
    averageScore: 92.5,
    year: 2019,
    image: "/posters/poster-pousando-no-amor.jpg",
    description: "Uma herdeira sul-coreana cai acidentalmente na Coreia do Norte após um incidente de parapente e encontra um oficial do exército que decide ajudá-la a se esconder.",
    category: "Romance / Comédia",
    review: "O equilíbrio perfeito entre romance, comédia e drama político. A química entre os protagonistas é de outro mundo. Um clássico moderno que todo mundo deveria ver."
  },
  { 
    rank: 4, 
    title: "Sr. Rainha", 
    original: "Mr. Queen", 
    imdb: 8.6, 
    adoroCinema: 4.8,
    popularity: 97,
    averageScore: 91,
    year: 2020,
    image: "/posters/poster-sr-rainha.jpg",
    description: "Um chef de cozinha dos tempos modernos viaja no tempo e acaba no corpo de uma rainha da era Joseon.",
    category: "Comédia / Histórico / Fantasia",
    review: "Divertido do início ao fim! A atuação da protagonista é simplesmente genial, conseguindo transmitir perfeitamente a alma de um homem moderno em um corpo real. Uma das melhores comédias já feitas."
  },
  { 
    rank: 5, 
    title: "Uma Advogada Extraordinária", 
    original: "Extraordinary Attorney Woo", 
    imdb: 8.7, 
    adoroCinema: 4.7,
    popularity: 98,
    averageScore: 90.5,
    year: 2022,
    image: "/posters/poster-uma-advogada-extraordinaria.jpg",
    description: "Uma advogada brilhante no espectro autista enfrenta desafios no tribunal e na vida cotidiana.",
    category: "Drama / Jurídico"
  },
  { 
    rank: 6, 
    title: "Twinkling Watermelon", 
    original: "Twinkling Watermelon", 
    imdb: 8.9, 
    adoroCinema: 4.6,
    popularity: 90,
    averageScore: 90.5,
    year: 2023,
    image: "/posters/poster-twinkling-watermelon.jpg",
    description: "Um jovem CODA viaja no tempo para 1995 e forma uma banda com seu pai adolescente.",
    category: "Juventude / Fantasia"
  },
  { 
    rank: 7, 
    title: "Hospital Playlist", 
    original: "Hospital Playlist", 
    imdb: 8.8, 
    adoroCinema: 4.6,
    popularity: 92,
    averageScore: 90,
    year: 2020,
    image: "/posters/poster-hospital-playlist.jpg",
    description: "Cinco médicos que são amigos desde a faculdade compartilham seu amor pela música e os desafios do dia a dia no hospital.",
    category: "Drama / Médico"
  },
  { 
    rank: 8, 
    title: "Seis Dragões Voadores", 
    original: "Six Flying Dragons", 
    imdb: 8.8, 
    adoroCinema: 4.5,
    popularity: 84,
    averageScore: 89,
    year: 2015,
    image: "/posters/poster-six-flying-dragons.jpg",
    description: "A história da fundação da dinastia Joseon e as ambições de seis figuras-chave.",
    category: "Histórico / Político"
  },
  { 
    rank: 9, 
    title: "My Dearest", 
    original: "My Dearest", 
    imdb: 8.9, 
    adoroCinema: 4.4,
    popularity: 92,
    averageScore: 88.5,
    year: 2023,
    image: "/posters/poster-my-dearest.png",
    description: "Uma história de amor épica ambientada durante a invasão Qing em Joseon.",
    category: "Histórico / Romance"
  },
  { 
    rank: 10, 
    title: "A Caminho do Céu", 
    original: "Move to Heaven", 
    imdb: 8.5, 
    adoroCinema: 4.8,
    popularity: 90,
    averageScore: 90.5,
    year: 2021,
    image: "/posters/poster-a-caminho-do-ceu.png",
    description: "Um jovem com síndrome de Asperger e seu tio trabalham como limpadores de trauma, contando as histórias dos falecidos.",
    category: "Drama / Vida"
  },
  { rank: 11, title: "Mr. Sunshine: Um Raio de Sol", original: "Mr. Sunshine", imdb: 8.7, adoroCinema: 4.8, popularity: 91, averageScore: 91, year: 2018, description: "Um jovem coreano que fugiu para os EUA retorna à sua terra natal como oficial da marinha americana e se apaixona por uma aristocrata.", image: "/posters/poster-mr-sunshine.png", category: "Histórico / Drama" },
  { rank: 12, title: "Lovely Runner", original: "Lovely Runner", imdb: 8.7, adoroCinema: 4.8, popularity: 97, averageScore: 91, year: 2024, description: "Uma fã viaja no tempo para salvar seu ídolo favorito de um destino trágico.", image: "/posters/poster-adoravel-corredora.png", category: "Romance / Fantasia" },
  { rank: 13, title: "Vinte e Cinco, Vinte e Um", original: "Twenty-Five Twenty-One", imdb: 8.6, adoroCinema: 4.8, popularity: 97, averageScore: 91, year: 2022, description: "Em uma época de crise financeira, uma esgrimista adolescente e um jovem trabalhador lutam por seus sonhos e descobrem o amor.", image: "/posters/poster-vinte-e-cinco-vinte-e-um.png", category: "Romance / Juventude" },
  { rank: 14, title: "A Lição: Parte 2", original: "The Glory Part 2", imdb: 8.4, adoroCinema: 4.9, popularity: 99, averageScore: 91, year: 2023, description: "A conclusão épica da vingança de Moon Dong-eun contra seus algozes de infância.", image: "/posters/poster-a-licao-parte-2.jpg", category: "Suspense / Vingança" },
  { rank: 15, title: "Mouse", original: "Mouse", imdb: 8.7, adoroCinema: 4.7, popularity: 88, averageScore: 90.5, year: 2021, description: "Um policial honesto e um detetive endurecido caçam um serial killer psicopata que aterroriza a nação.", image: "/posters/poster-mouse.png", category: "Crime / Mistério" },
  { rank: 16, title: "Flor do Mal", original: "Flower of Evil", imdb: 8.6, adoroCinema: 4.8, popularity: 92, averageScore: 90.5, year: 2020, description: "Uma detetive descobre que seu marido perfeito pode estar escondendo um passado sombrio e uma identidade falsa.", image: "/posters/poster-flor-do-mal.jpg", category: "Suspense / Romance" },
  { rank: 17, title: "Weak Hero Class 1", original: "Weak Hero Class 1", imdb: 8.6, adoroCinema: 4.8, popularity: 93, averageScore: 90.5, year: 2022, description: "Um estudante modelo usa sua inteligência e psicologia para lutar contra a violência escolar.", image: "/posters/poster-weak-hero-class-1.png", category: "Ação / Escolar" },
  { rank: 18, title: "Moving", original: "Moving", imdb: 8.5, adoroCinema: 4.8, popularity: 97, averageScore: 90.5, year: 2023, description: "Adolescentes com superpoderes e seus pais, que escondem segredos dolorosos do passado, enfrentam grandes perigos.", image: "/posters/poster-moving.png", category: "Ação / Sci-Fi" },
  { rank: 19, title: "Goblin: O Solitário e Grande Deus", original: "Guardian: The Lonely and Great God", imdb: 8.6, adoroCinema: 4.7, popularity: 97, averageScore: 90, year: 2016, description: "Um guerreiro imortal precisa encontrar sua noiva humana para acabar com sua vida eterna, mas acaba se apaixonando por ela no processo.", image: "/posters/poster-goblin.png", category: "Fantasia / Romance" },
  { rank: 20, title: "Misaeng: Incomplete Life", original: "Misaeng: Incomplete Life", imdb: 8.6, adoroCinema: 4.7, popularity: 85, averageScore: 90, year: 2014, description: "Um ex-jogador de Go começa a trabalhar em uma grande empresa comercial e enfrenta a dura realidade do mundo corporativo.", image: "/posters/poster-misaeng.png", category: "Negócios / Vida" },
  { rank: 21, title: "O Jogo da Morte", original: "Death's Game", imdb: 8.6, adoroCinema: 4.7, popularity: 94, averageScore: 90, year: 2023, description: "Um homem recebe 12 chances de viver e morrer após insultar a própria Morte.", image: "/posters/poster-o-jogo-da-morte.png", category: "Fantasia / Suspense" },
  { rank: 22, title: "Alquimia das Almas", original: "Alchemy of Souls", imdb: 8.8, adoroCinema: 4.6, popularity: 96, averageScore: 89.5, year: 2022, description: "Uma feiticeira poderosa no corpo de uma mulher cega encontra um homem de uma família prestigiosa, que deseja sua ajuda para mudar seu destino.", image: "/posters/poster-alquimia-das-almas.jpg", category: "Fantasia / Ação" },
  { rank: 23, title: "Signal", original: "Signal", imdb: 8.5, adoroCinema: 4.7, popularity: 89, averageScore: 89.5, year: 2016, description: "Detetives do presente e do passado se comunicam através de um walkie-talkie misterioso para resolver crimes antigos.", image: "/posters/poster-signal.png", category: "Crime / Mistério" },
  { rank: 24, title: "Stranger", original: "Stranger", imdb: 8.5, adoroCinema: 4.7, popularity: 87, averageScore: 89.5, year: 2017, description: "Um promotor frio e sem emoções trabalha com uma detetive corajosa para desvendar a corrupção no governo.", image: "/posters/poster-stranger.jpg", category: "Crime / Suspense" },
  { rank: 25, title: "Papel de Rainha", original: "Under the Queen's Umbrella", imdb: 8.5, adoroCinema: 4.7, popularity: 89, averageScore: 89.5, year: 2022, description: "Uma rainha tenta transformar seus filhos problemáticos em príncipes dignos em meio a intrigas palacianas.", image: "/posters/poster-sob-o-papel-da-rainha.jpg", category: "Histórico / Drama" },
  { rank: 26, title: "Vincenzo", original: "Vincenzo", imdb: 8.4, adoroCinema: 4.8, popularity: 94, averageScore: 89.5, year: 2021, description: "Um advogado coreano que trabalha para a máfia italiana se envolve em uma batalha contra um conglomerado farmacêutico maligno ao visitar sua terra natal.", image: "/posters/poster-vincenzo.jpg", category: "Crime / Comédia Ácida" },
  { rank: 27, title: "Kingdom", original: "Kingdom", imdb: 8.3, adoroCinema: 4.8, popularity: 96, averageScore: 89.5, year: 2019, description: "Em plena era Joseon, um príncipe herdeiro investiga uma praga misteriosa que transforma as pessoas em monstros.", image: "/posters/poster-kingdom.png", category: "Terror / Histórico" },
  { rank: 28, title: "Tudo Bem Não Ser Normal", original: "It's Okay to Not Be Okay", imdb: 8.6, adoroCinema: 4.6, popularity: 95, averageScore: 89, year: 2020, description: "Um cuidador de uma ala psiquiátrica e uma escritora de livros infantis com transtorno de personalidade antissocial ajudam um ao outro a curar feridas emocionais.", image: "/posters/poster-tudo-bem-nao-ser-normal.png", category: "Drama / Romance" },
  { rank: 29, title: "Tale of the Nine Tailed 1938", original: "Tale of the Nine Tailed 1938", imdb: 8.6, adoroCinema: 4.6, popularity: 91, averageScore: 89, year: 2023, description: "A raposa de nove caudas viaja no tempo para 1938 e luta para retornar ao presente.", image: "/posters/poster-tale-of-the-nine-tailed.png", category: "Fantasia / Ação" },
  { rank: 30, title: "Uma Dose Diária de Sol", original: "Daily Dose of Sunshine", imdb: 8.3, adoroCinema: 4.8, popularity: 89, averageScore: 89, year: 2023, description: "Uma enfermeira dedicada tenta trazer luz para a vida dos pacientes em uma ala psiquiátrica.", image: "/posters/poster-uma-dose-diaria-de-sol.jpg", category: "Drama / Médico" },
  { rank: 31, title: "My Name", original: "My Name", imdb: 7.8, adoroCinema: 5.0, popularity: 92, averageScore: 89, year: 2021, description: "Uma mulher busca vingança pela morte do pai e se infiltra na polícia sob as ordens de um chefe do crime.", image: "/posters/poster-my-name.jpg", category: "Ação / Crime" },
  { rank: 32, title: "Moon Lovers: Scarlet Heart Ryeo", original: "Moon Lovers: Scarlet Heart Ryeo", imdb: 8.6, adoroCinema: 4.6, popularity: 96, averageScore: 88.5, year: 2016, description: "Uma mulher do século 21 viaja no tempo para a era Goryeo e se envolve em uma disputa política e romântica entre príncipes.", image: "/posters/poster-scarlet-heart-ryeo.png", category: "Histórico / Fantasia" },
  { rank: 33, title: "Healer", original: "Healer", imdb: 8.5, adoroCinema: 4.6, popularity: 89, averageScore: 88.5, year: 2014, description: "Um mensageiro noturno misterioso, uma repórter e um jornalista famoso se unem para desvendar um incidente de décadas atrás.", image: "/posters/poster-healer.png", category: "Ação / Romance" },
  { rank: 34, title: "Manual do Presidiário", original: "Prison Playbook", imdb: 8.4, adoroCinema: 4.7, popularity: 87, averageScore: 88.5, year: 2017, description: "Um jogador de beisebol famoso acaba na prisão e precisa aprender a sobreviver em um ambiente hostil.", image: "/posters/poster-manual-do-presidiario.png", category: "Comédia / Drama" },
  { rank: 35, title: "D.P. Dog Day", original: "D.P.", imdb: 8.2, adoroCinema: 4.8, popularity: 87, averageScore: 88.5, year: 2021, description: "Soldados coreanos são designados para capturar desertores do exército e enfrentam a dura realidade do serviço militar.", image: "/posters/poster-dp-dog-day.png", category: "Militar / Drama" },
  { rank: 36, title: "A Lição", original: "The Glory", imdb: 8.1, adoroCinema: 4.8, popularity: 99, averageScore: 88.5, year: 2022, description: "Anos depois de ser vítima de terríveis agressões na escola, uma mulher coloca em prática um elaborado plano de vingança contra seus antigos algozes.", image: "/posters/poster-a-licao.jpg", category: "Suspense / Vingança" },
  { rank: 37, title: "The Good Bad Mother", original: "The Good Bad Mother", imdb: 8.4, adoroCinema: 4.6, popularity: 91, averageScore: 88, year: 2023, description: "Uma mãe rigorosa e seu filho promotor têm uma segunda chance de reconstruir sua relação após um acidente trágico.", image: "/posters/poster-the-good-bad-mother.png", category: "Drama / Família" },
  { rank: 38, title: "Hometown Cha-Cha-Cha", original: "Hometown Cha-Cha-Cha", imdb: 8.4, adoroCinema: 4.6, popularity: 91, averageScore: 87.5, year: 2021, description: "Uma dentista da cidade grande abre um consultório em uma vila litorânea e se envolve com um faz-tudo local que ajuda a todos.", image: "/posters/poster-hometown-cha-cha-cha.png", category: "Romance / Comédia" },
  { rank: 39, title: "Queen of Tears", original: "Queen of Tears", imdb: 8.3, adoroCinema: 4.6, popularity: 99, averageScore: 87.5, year: 2024, description: "A rainha das lojas de departamento e o príncipe dos supermercados enfrentam uma crise conjugal e descobrem o amor novamente.", image: "/posters/poster-rainha-das-lagrimas.png", category: "Romance / Drama" },
  { rank: 40, title: "Round 6", original: "Squid Game", imdb: 8, adoroCinema: 4.8, popularity: 100, averageScore: 87.5, year: 2021, description: "Centenas de jogadores falidos aceitam um convite estranho para competir em jogos infantis por um prêmio milionário, mas as apostas são fatais.", image: "/posters/poster-round-6.png", category: "Suspense / Drama" },
  { rank: 41, title: "A Fada do Levantamento de Peso, Kim Bok-joo", original: "Weightlifting Fairy Kim Bok-joo", imdb: 8.4, adoroCinema: 4.5, popularity: 93, averageScore: 87, year: 2016, description: "Uma jovem levantadora de peso e um nadador talentoso descobrem o amor e enfrentam os desafios da vida universitária.", image: "/posters/poster-a-fada-do-levantamento-de-peso.jpg", category: "Esporte / Romance" },
  { rank: 42, title: "O Pior do Mal", original: "The Worst of Evil", imdb: 8.3, adoroCinema: 4.5, popularity: 89, averageScore: 86.5, year: 2023, description: "Um policial se infiltra em uma organização criminosa internacional de tráfico de drogas.", image: "/posters/poster-o-pior-do-mal.jpg", category: "Crime / Ação" },
  { rank: 43, title: "Além do Mal", original: "Beyond Evil", imdb: 8.1, adoroCinema: 4.6, popularity: 86, averageScore: 86.5, year: 2021, description: "Dois policiais de uma pequena cidade investigam um caso de assassinato que lembra um crime ocorrido há 20 anos.", image: "/posters/poster-alem-do-mal.jpg", category: "Crime / Psicológico" },
  { rank: 44, title: "Pretendente Surpresa", original: "Business Proposal", imdb: 8.1, adoroCinema: 4.6, popularity: 98, averageScore: 86.5, year: 2022, description: "Uma funcionária vai a um encontro às cegas no lugar da amiga e descobre que o pretendente é o CEO da sua empresa.", image: "/posters/poster-pretendente-surpresa.jpg", category: "Romance / Comédia" },
  { rank: 45, title: "Mask Girl", original: "Mask Girl", imdb: 7.3, adoroCinema: 5.0, popularity: 90, averageScore: 86.5, year: 2023, description: "Uma funcionária de escritório insegura com sua aparência vive uma vida dupla como uma personalidade mascarada na internet.", image: "/posters/poster-mask-girl.png", category: "Suspense / Crime" },
  { rank: 46, title: "Dr. Romântico", original: "Dr. Romantic", imdb: 8.3, adoroCinema: 4.5, popularity: 91, averageScore: 86, year: 2016, description: "Um cirurgião famoso desaparece e reaparece em um hospital pequeno, onde ensina jovens médicos a serem verdadeiros doutores.", image: "/posters/poster-dr-romatico.jpg", category: "Médico / Drama" },
  { rank: 47, title: "Descendentes do Sol", original: "Descendants of the Sun", imdb: 8.2, adoroCinema: 4.5, popularity: 93, averageScore: 86, year: 2016, description: "Um capitão das forças especiais e uma médica se apaixonam enquanto trabalham em um país devastado pela guerra.", image: "/posters/poster-descendentes-do-sol.jpg", category: "Ação / Romance" },
  { rank: 48, title: "Nosso Eterno Verão", original: "Our Beloved Summer", imdb: 8.2, adoroCinema: 4.5, popularity: 94, averageScore: 86, year: 2021, description: "Anos após gravarem um documentário viral na escola, dois ex-namorados são forçados a se reencontrar diante das câmeras.", image: "/posters/poster-nosso-eterno-verao.jpg", category: "Romance / Comédia" },
  { rank: 49, title: "Diga que é Amor", original: "Call It Love", imdb: 8.2, adoroCinema: 4.5, popularity: 81, averageScore: 86, year: 2023, description: "Uma mulher busca vingança contra a amante de seu falecido pai, mas acaba se apaixonando pelo filho dela.", image: "/posters/poster-diga-que-e-amor.png", category: "Romance / Melodrama" },
  { rank: 50, title: "Justiça Juvenil", original: "Juvenile Justice", imdb: 8, adoroCinema: 4.6, popularity: 85, averageScore: 86, year: 2022, description: "Uma juíza que detesta criminosos juvenis é designada para um tribunal de menores.", image: "/posters/poster-justica-juvenil.jpg", category: "Jurídico / Drama" },
  { rank: 51, title: "Enquanto Você Dormia", original: "While You Were Sleeping", imdb: 8.3, adoroCinema: 4.4, popularity: 92, averageScore: 85.5, year: 2017, description: "Uma mulher que pode ver o futuro em seus sonhos conhece um promotor que tenta impedir que esses sonhos se tornem realidade.", image: "/posters/poster-enquanto-voce-dormia.jpg", category: "Fantasia / Romance" },
  { rank: 52, title: "Hotel Del Luna", original: "Hotel Del Luna", imdb: 8.2, adoroCinema: 4.5, popularity: 94, averageScore: 85.5, year: 2019, description: "Uma hoteleira amaldiçoada gerencia um hotel para fantasmas e contrata um gerente humano para ajudá-la.", image: "/posters/poster-hotel-del-luna.png", category: "Fantasia / Romance" },
  { rank: 53, title: "Cães de Caça", original: "Bloodhounds", imdb: 8.1, adoroCinema: 4.5, popularity: 93, averageScore: 85.5, year: 2023, description: "Dois jovens boxeadores se unem a um agiota benevolente para derrubar um agiota cruel que ataca os vulneráveis.", image: "/posters/poster-caes-de-caca.jpg", category: "Ação / Crime" },
  { rank: 54, title: "Uma Loja para Assassinos", original: "A Shop for Killers", imdb: 8.1, adoroCinema: 4.5, popularity: 92, averageScore: 85.5, year: 2024, description: "Uma jovem descobre a perigosa herança de seu tio após sua morte repentina.", image: "/posters/poster-uma-loja-para-assassinos.png", category: "Ação / Suspense" },
  { rank: 55, title: "Diva à Deriva", original: "Castaway Diva", imdb: 8.1, adoroCinema: 4.5, popularity: 88, averageScore: 85.5, year: 2023, description: "Uma aspirante a cantora é resgatada de uma ilha deserta após 15 anos e tenta se ajustar à sociedade moderna.", image: "/posters/poster-diva-a-deriva.png", category: "Drama / Musical" },
  { rank: 56, title: "Itaewon Class", original: "Itaewon Class", imdb: 8.2, adoroCinema: 4.4, popularity: 92, averageScore: 85, year: 2020, description: "Um ex-presidiário abre um bar-restaurante em Itaewon e busca vingança contra o conglomerado que destruiu sua vida.", image: "/posters/poster-itaewon-class.png", category: "Drama / Vingança" },
  { rank: 57, title: "Investigador Chefe 1958", original: "Chief Detective 1958", imdb: 8.2, adoroCinema: 4.4, popularity: 85, averageScore: 85, year: 2024, description: "Um detetive apaixonado luta contra a corrupção em uma era turbulenta.", image: "/posters/poster-chief-detective-1958.png", category: "Crime / Histórico" },
  { rank: 58, title: "O Que Houve com a Secretária Kim?", original: "What's Wrong with Secretary Kim", imdb: 8.1, adoroCinema: 4.4, popularity: 93, averageScore: 84.5, year: 2018, description: "Um vice-presidente narcisista entra em pânico quando sua secretária perfeita decide pedir demissão após nove anos.", image: "/posters/poster-o-que-houve-com-a-secretaria-kim.png", category: "Romance / Comédia" },
  { rank: 59, title: "Taxi Driver", original: "Taxi Driver", imdb: 8, adoroCinema: 4.4, popularity: 93, averageScore: 84, year: 2021, description: "Um serviço de táxi misterioso oferece vingança para vítimas que a lei não conseguiu proteger.", image: "/posters/poster-taxi-driver.jpg", category: "Ação / Crime" },
  { rank: 60, title: "Welcome to Samdal-ri", original: "Welcome to Samdal-ri", imdb: 8, adoroCinema: 4.4, popularity: 92, averageScore: 84, year: 2023, description: "Uma fotógrafa de sucesso retorna à sua cidade natal após um escândalo e reencontra seu amigo de infância.", image: "/posters/poster-de-volta-as-raizes-samdal-ri.jpg", category: "Romance / Drama" },
  { rank: 61, title: "Strong Woman Do Bong-soon", original: "Strong Woman Do Bong-soon", imdb: 8.2, adoroCinema: 4.3, popularity: 94, averageScore: 83.5, year: 2017, description: "Uma mulher com força sobre-humana é contratada como guarda-costas de um CEO de uma empresa de jogos.", image: "https://picsum.photos/seed/strongwoman/400/600", category: "Comédia / Fantasia" },
  { rank: 62, title: "Renascendo Rico", original: "Reborn Rich", imdb: 8.1, adoroCinema: 4.3, popularity: 96, averageScore: 83, year: 2022, description: "Um funcionário leal é morto por sua empresa e renasce como o neto mais novo da família fundadora, buscando vingança.", image: "https://picsum.photos/seed/reborn/400/600", category: "Fantasia / Vingança" },
  { rank: 63, title: "As Três Irmãs", original: "Little Women", imdb: 7.8, adoroCinema: 4.4, popularity: 91, averageScore: 83, year: 2022, description: "Três irmãs pobres se envolvem em uma conspiração que as coloca contra a família mais rica da Coreia.", image: "https://picsum.photos/seed/littlewomen/400/600", category: "Mistério / Drama" },
  { rank: 64, title: "Extracurricular", original: "Extracurricular", imdb: 7.6, adoroCinema: 4.5, popularity: 88, averageScore: 83, year: 2020, description: "Um estudante modelo se envolve em um mundo de crimes graves para pagar seus estudos.", image: "https://picsum.photos/seed/extra/400/600", category: "Crime / Escolar" },
  { rank: 65, title: "Beleza Verdadeira", original: "True Beauty", imdb: 8, adoroCinema: 4.3, popularity: 94, averageScore: 82.5, year: 2020, description: "Uma colegial que sofre bullying por sua aparência domina a arte da maquiagem e se torna a garota mais bonita da escola.", image: "https://picsum.photos/seed/truebeauty/400/600", category: "Romance / Escolar" },
  { rank: 66, title: "Start-Up", original: "Start-Up", imdb: 8, adoroCinema: 4.3, popularity: 95, averageScore: 82.5, year: 2020, description: "Jovens empreendedores competem no Vale do Silício da Coreia para transformar seus sonhos em realidade.", image: "https://picsum.photos/seed/startup/400/600", category: "Negócios / Romance" },
  { rank: 67, title: "W: Two Worlds", original: "W: Two Worlds", imdb: 8, adoroCinema: 4.2, popularity: 91, averageScore: 82, year: 2016, description: "Um cirurgião é puxado para dentro de um webtoon e se apaixona pelo protagonista da história.", image: "https://picsum.photos/seed/w/400/600", category: "Fantasia / Suspense" },
  { rank: 68, title: "O Rei de Porcelana", original: "The King's Affection", imdb: 7.9, adoroCinema: 4.3, popularity: 89, averageScore: 82, year: 2021, description: "Quando o príncipe herdeiro é morto, sua irmã gêmea assume o trono enquanto tenta esconder sua identidade de todos.", image: "https://picsum.photos/seed/kingaffection/400/600", category: "Histórico / Romance" },
  { rank: 69, title: "A Esposa do Meu Marido", original: "Marry My Husband", imdb: 7.9, adoroCinema: 4.3, popularity: 98, averageScore: 82, year: 2024, description: "Uma mulher traída e assassinada viaja 10 anos no passado para mudar seu destino e se vingar.", image: "https://picsum.photos/seed/marry/400/600", category: "Romance / Vingança" },
  { rank: 70, title: "O Tempo Traz Você pra Mim", original: "A Time Called You", imdb: 7.8, adoroCinema: 4.3, popularity: 88, averageScore: 81.5, year: 2023, description: "Uma mulher viaja no tempo para 1998 e conhece um homem que se parece exatamente com seu falecido namorado.", image: "https://picsum.photos/seed/time/400/600", category: "Romance / Fantasia" },
  { rank: 71, title: "All of Us Are Dead", original: "All of Us Are Dead", imdb: 7.5, adoroCinema: 4.4, popularity: 99, averageScore: 81.5, year: 2022, description: "Estudantes ficam presos em uma escola durante um surto de vírus zumbi e precisam lutar para sobreviver.", image: "https://picsum.photos/seed/zombie/400/600", category: "Terror / Escolar" },
  { rank: 72, title: "Profecia do Inferno", original: "Hellbound", imdb: 6.6, adoroCinema: 4.9, popularity: 89, averageScore: 81.5, year: 2021, description: "Criaturas sobrenaturais aparecem para condenar pessoas ao inferno, dando origem a um grupo religioso radical.", image: "https://picsum.photos/seed/hellbound/400/600", category: "Terror / Sobrenatural" },
  { rank: 73, title: "Celebridade", original: "Celebrity", imdb: 7.4, adoroCinema: 4.4, popularity: 94, averageScore: 81, year: 2023, description: "Uma jovem mergulha no mundo glamouroso e perigoso dos influenciadores digitais de Seul.", image: "https://picsum.photos/seed/celebrity/400/600", category: "Mistério / Drama" },
  { rank: 74, title: "O Som da Magia", original: "The Sound of Magic", imdb: 7.6, adoroCinema: 4.3, popularity: 84, averageScore: 80.5, year: 2022, description: "Um mágico misterioso que vive em um parque de diversões abandonado ajuda uma estudante a redescobrir seus sonhos.", image: "https://picsum.photos/seed/magic/400/600", category: "Musical / Fantasia" },
  { rank: 75, title: "Vigilante", original: "Vigilante", imdb: 7.8, adoroCinema: 4.1, popularity: 88, averageScore: 80, year: 2023, description: "Um estudante da academia de polícia vive uma vida dupla como um vigilante que pune criminosos.", image: "https://picsum.photos/seed/vigilante/400/600", category: "Ação / Crime" },
  { rank: 76, title: "Dra. Cha", original: "Doctor Cha", imdb: 7.5, adoroCinema: 4.3, popularity: 92, averageScore: 80, year: 2023, description: "Uma dona de casa decide retomar sua carreira médica como residente após 20 anos.", image: "https://picsum.photos/seed/drcha/400/600", category: "Médico / Comédia" },
  { rank: 77, title: "The Penthouse", original: "The Penthouse: War in Life", imdb: 7.9, adoroCinema: 4.0, popularity: 96, averageScore: 79.5, year: 2020, description: "Famílias ricas vivendo em um arranha-céu de luxo fazem de tudo para proteger seus filhos e seu status social.", image: "https://picsum.photos/seed/penthouse/400/600", category: "Drama / Suspense" },
  { rank: 78, title: "Uma Família Atípica", original: "The Atypical Family", imdb: 7.7, adoroCinema: 4.1, popularity: 91, averageScore: 79.5, year: 2024, description: "Uma família com superpoderes perde suas habilidades devido a problemas modernos, até que uma mulher misteriosa aparece.", image: "https://picsum.photos/seed/atypical/400/600", category: "Fantasia / Romance" },
  { rank: 79, title: "Sorriso Real", original: "King the Land", imdb: 7.8, adoroCinema: 4.0, popularity: 95, averageScore: 79, year: 2023, description: "Um herdeiro charmoso e uma funcionária sorridente se envolve em um romance em um hotel de luxo.", image: "https://picsum.photos/seed/kingland/400/600", category: "Romance / Comédia" },
  { rank: 80, title: "Midnight Studio", original: "The Midnight Studio", imdb: 7.8, adoroCinema: 4.0, popularity: 82, averageScore: 79, year: 2024, description: "Um fotógrafo solitário que tira fotos de fantasmas conhece uma advogada apaixonada.", image: "https://picsum.photos/seed/midnight/400/600", category: "Fantasia / Romance" },
  { rank: 81, title: "A Criatura de Gyeongseong", original: "Gyeongseong Creature", imdb: 7.3, adoroCinema: 4.3, popularity: 96, averageScore: 79, year: 2023, description: "Em 1945, em Gyeongseong, um empresário e uma investigadora lutam pela sobrevivência contra um monstro nascido da ganância humana.", image: "https://picsum.photos/seed/creature/400/600", category: "Terror / Histórico" },
  { rank: 82, title: "Bora! Deborah", original: "Bora! Deborah", imdb: 7.7, adoroCinema: 4.0, popularity: 83, averageScore: 78.5, year: 2023, description: "Uma famosa coach de namoro precisa lidar com o fracasso de seu próprio relacionamento.", image: "https://picsum.photos/seed/deborah/400/600", category: "Romance / Comédia" },
  { rank: 83, title: "Médicos em Colapso", original: "Doctor Slump", imdb: 7.4, adoroCinema: 4.1, popularity: 93, averageScore: 78, year: 2024, description: "Dois médicos rivais que estão em momentos difíceis de suas vidas se reencontram e encontram conforto um no outro.", image: "https://picsum.photos/seed/slump/400/600", category: "Romance / Médico" },
  { rank: 84, title: "Sweet Home", original: "Sweet Home", imdb: 7.3, adoroCinema: 4.2, popularity: 96, averageScore: 78, year: 2020, description: "Moradores de um prédio lutam para sobrevivem quando humanos começam a se transformar em monstros que refletem seus desejos internos.", image: "https://picsum.photos/seed/sweethome/400/600", category: "Terror / Ação" },
  { rank: 85, title: "The Midnight Romance in Hagwon", original: "The Midnight Romance in Hagwon", imdb: 7.5, adoroCinema: 4.0, popularity: 84, averageScore: 77.5, year: 2024, description: "Um romance secreto entre uma instrutora veterana e seu ex-aluno que retorna como instrutor novato.", image: "https://picsum.photos/seed/hagwon/400/600", category: "Romance / Drama" },
  { rank: 86, title: "Parasyte: The Grey", original: "Parasyte: The Grey", imdb: 7, adoroCinema: 4.3, popularity: 95, averageScore: 77.5, year: 2024, description: "Formas de vida parasitas caem do espaço e começam a dominar os humanos, mas uma mulher desenvolve uma coexistência estranha com seu parasita.", image: "https://picsum.photos/seed/parasyte/400/600", category: "Sci-Fi / Terror" },
  { rank: 87, title: "Behind Your Touch", original: "Behind Your Touch", imdb: 7.3, adoroCinema: 4.0, popularity: 86, averageScore: 76.5, year: 2023, description: "Uma veterinária com poderes psicométricos e um detetive se unem para resolver crimes em uma pequena cidade.", image: "https://picsum.photos/seed/touch/400/600", category: "Comédia / Mistério" },
  { rank: 88, title: "The 8 Show", original: "The 8 Show", imdb: 7.2, adoroCinema: 4.0, popularity: 93, averageScore: 76, year: 2024, description: "Oito pessoas presas em um prédio de oito andares participam de um reality show perigoso onde o tempo é dinheiro.", image: "https://picsum.photos/seed/8show/400/600", category: "Suspense / Drama" },
  { rank: 89, title: "Song of the Bandits", original: "Song of the Bandits", imdb: 7.2, adoroCinema: 4.0, popularity: 85, averageScore: 76, year: 2023, description: "Bandidos coreanos lutam para proteger sua terra e seus entes queridos em Gando durante a ocupação japonesa.", image: "https://picsum.photos/seed/bandits/400/600", category: "Ação / Histórico" },
  { rank: 90, title: "A Killer Paradox", original: "A Killer Paradox", imdb: 7.2, adoroCinema: 4.0, popularity: 91, averageScore: 76, year: 2024, description: "Um estudante universitário mata acidentalmente um serial killer e descobre que tem a habilidade de identificar pessoas más.", image: "https://picsum.photos/seed/paradox/400/600", category: "Suspense / Crime" },
  { rank: 91, title: "Doona!", original: "Doona!", imdb: 7.1, adoroCinema: 4.0, popularity: 95, averageScore: 75.5, year: 2023, description: "Um estudante universitário comum começa a morar com uma ex-estrela do K-pop em uma casa compartilhada.", image: "https://picsum.photos/seed/doona/400/600", category: "Romance / Drama" },
  { rank: 92, title: "Sisyphus: The Myth", original: "Sisyphus: The Myth", imdb: 7, adoroCinema: 3.8, popularity: 80, averageScore: 72.5, year: 2021, description: "Um engenheiro genial tenta descobrir a verdade por trás da morte de seu irmão e conhece uma mulher misteriosa do futuro.", image: "https://picsum.photos/seed/sisyphus/400/600", category: "Sci-Fi / Ação" },
  { rank: 93, title: "Island", original: "Island", imdb: 6.9, adoroCinema: 3.8, popularity: 84, averageScore: 72, year: 2022, description: "Três pessoas improváveis se unem na Ilha de Jeju para lutar contra demônios que ameaçam destruir o mundo.", image: "https://picsum.photos/seed/island/400/600", category: "Fantasia / Ação" },
  { rank: 94, title: "Frankly Speaking", original: "Frankly Speaking", imdb: 6.5, adoroCinema: 3.5, popularity: 80, averageScore: 67.5, year: 2024, description: "Um locutor respeitado perde a habilidade de mentir e começa a falar tudo o que pensa.", image: "https://picsum.photos/seed/frankly/400/600", category: "Comédia / Romance" },
  { rank: 95, title: "Sweet Home Season 2", original: "Sweet Home Season 2", imdb: 6.4, adoroCinema: 3.5, popularity: 94, averageScore: 67, year: 2023, description: "A luta pela sobrevivência continua fora do Green Home, com novos monstros e novos desafios.", image: "https://picsum.photos/seed/sweethome2/400/600", category: "Terror / Ação" },
  { rank: 96, title: "The Interest of Love", original: "The Interest of Love", imdb: 6.3, adoroCinema: 3.5, popularity: 82, averageScore: 66.5, year: 2022, description: "Quatro funcionários de um banco se envolvem em relacionamentos complicados enquanto buscam o verdadeiro significado do amor.", image: "https://picsum.photos/seed/interest/400/600", category: "Romance / Drama" },
  { rank: 97, title: "Hierarchy", original: "Hierarchy", imdb: 6, adoroCinema: 3.3, popularity: 94, averageScore: 62.5, year: 2024, description: "O segredo de uma escola de elite começa a ser revelado quando um novo aluno se transfere.", image: "https://picsum.photos/seed/hierarchy/400/600", category: "Escolar / Mistério" },
  { rank: 98, title: "La Casa de Papel: Coreia", original: "Money Heist: Korea - Joint Economic Area", imdb: 5.4, adoroCinema: 3.0, popularity: 90, averageScore: 57, year: 2022, description: "Ladrões planejam um assalto ambicioso na península coreana unificada.", image: "https://picsum.photos/seed/moneyheist/400/600", category: "Ação / Crime" },
  { rank: 99, title: "Chicken Nugget", original: "Chicken Nugget", imdb: 5, adoroCinema: 3.0, popularity: 85, averageScore: 55, year: 2024, description: "Um pai tenta transformar sua filha de volta em humana após ela se transformar em um nugget de frango.", image: "https://picsum.photos/seed/nugget/400/600", category: "Comédia / Fantasia" },
  { rank: 100, title: "The King: Eternal Monarch", original: "The King: Eternal Monarch", imdb: 8.1, adoroCinema: 4.5, popularity: 90, averageScore: 83, year: 2020, description: "Um imperador coreano moderno atravessa um portal misterioso para um universo paralelo, onde conhece uma detetive de polícia obstinada.", image: "https://picsum.photos/seed/theking/400/600", category: "Romance / Fantasia" }
];
